language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"

install:
  - "wget http://download.gna.org/wkhtmltopdf/0.12/0.12.1/wkhtmltox-0.12.1_linux-precise-amd64.deb"
  - "sudo dpkg -i wkhtmltox-0.12.1_linux-precise-amd64.deb || true"
  - "wget http://nightly.odoo.com/8.0/nightly/deb/odoo_8.0.latest_all.deb"
  - "sudo dpkg -i odoo_8.0.latest_all.deb || true"
  - "sudo apt-get update && sudo apt-get install -f -y"
  - "sudo invoke-rc.d odoo stop"
  - pip install sphinx

before_script:
  - nohup /usr/bin/openerp-server -r $USER --addons-path=/usr/lib/python2.7/dist-packages/openerp/addons &
  - sleep 5

script:
  - python -m unittest discover -v
  - if [[ $TRAVIS_PYTHON_VERSION != 3.2 ]]; then PYTHONPATH=.:$PYTHONPATH sphinx-build -b doctest -d doc/build/doctrees doc/source build/doctest; fi
