language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

virtualenv:
  system_site_packages: true

env:
  - VERSION="8.0" ODOO_REPO="odoo/odoo"

install:
  - "wget http://freefr.dl.sourceforge.net/project/wkhtmltopdf/0.12.1/wkhtmltox-0.12.1_linux-trusty-amd64.deb"
  - "sudo dpkg -i wkhtmltox-0.12.1_linux-trusty-amd64.deb"
  - git clone https://github.com/OCA/maintainer-quality-tools.git $HOME/maintainer-quality-tools
  - export PATH=$HOME/maintainer-quality-tools/travis:$PATH
  - travis_install_nightly
  - pip install sphinx

before_script:
  - "nohup $HOME/odoo-$VERSION/openerp-server &"
  - sleep 10

script:
  - python -m unittest discover -v
